### ISSUE TITLE
"Exit after copying"  option leaves the user with a blank clipboard

### ISSUE THREAD

**Issue by ChildishGiant** [Merrit/feeling_finder#50] opened 2022-06-07 19:40 UTC
```
             ...-:::::-...                 allie@allie-desktop 
          .-MMMMMMMMMMMMMMM-.              ------------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 20.3 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Kernel: 5.4.0-113-generic 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Uptime: 5 hours, 21 mins 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Packages: 2202 (dpkg), 21 (flatpak) 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Shell: bash 5.0.17 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Resolution: 1920x1080, 1920x1080 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   DE: Cinnamon 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   WM: Mutter (Muffin) 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM Theme: Mint-Y-Dark-Purple (Mint-Y 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   Theme: Mint-Y-Dark-Purple [GTK2/3] 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Icons: Mint-Y-Dark-Purple [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Terminal: gnome-terminal 
   .MMM.MMMM:--------------:MMMM.MMM.      CPU: AMD Ryzen 5 1600X (12) @ 3.600G 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       GPU: AMD ATI Radeon RX 470/480/570/5 
       '.-MMMM``--:::::--``MMMM-.'         Memory: 5827MiB / 7949MiB 
            '-MMMMMMMMMMMMM-'
               ``-:::::-``                                                                                      
```

I can't paste it in *any* application.

**Comment by Merrit** [comment] 2022-06-08 01:28
Hi @ChildishGiant :wave: 
Thanks for opening the issue!

I can confirm the bug on my end. I'll take a look as soon as I get a chance. :+1:

**Comment by Merrit** [comment] 2022-06-08 14:52
Does this *always* fail to populate the clipboard for you, or only sometimes?

In my testing I can only seem to reproduce this once in a while, and most of the time it works normally.

**Comment by chrissigler** [comment] 2022-10-10 17:59
I'm also experiencing this problem, and consistently. However, I've noticed a few nuances that might be helpful in diagnostics.

First of all, I'm using Linux Mint 20.3 and launching FF using a keyboard shortcut that fires:

```flatpak run codes.merritt.FeelingFinder```

So here are a couple of my findings...

**1) The emoji is copied to the clipboard, but it's unavailable to paste.**   
I use Kupfer and its clipboard manager. So I can confirm that the emoji *is* sometimes copied to the clipboard initially (as Kupfer shows it in the clipboard history).

Interestingly, it even shows it's the *current* clipboard text. However, `Ctrl+v` doesn't actually paste anything, and a right-click context menu has a grayed out "Paste" as if it's null.


**2) Closing Feeling Finder manually has the same result if I use `Ctrl+w` or `Ctrl+q` to close FF.**   
If I disable "exit after copying" and launch FF, I can search and copy any number of emoji to my clipboard with my keyboard. If I then use `Ctrl+w` or `Ctrl+q` to close Feeling Finder, it will act just like if I'd had "exit after copying" enabled. That is, my clipboard history will show it, but I can't paste it.

If I instead use the mouse to close out the FF window, or even use `Alt+F4` on the keyboard, the emoji is able to be pasted.

**Comment by Merrit** [comment] 2022-10-10 19:57
Thanks so much for the info @chrissigler ! That information is very useful, I will take another look at the issue :smiley:

**Comment by Merrit** [comment] 2022-10-11 17:50
I checked and on Linux Mint 21 this isn't an issue, only on 20.3. Seems to be related to how [X11 handles the clipboard](https://wiki.ubuntu.com/ClipboardPersistence).

I've made a change that I think resolves the issue. @ChildishGiant @chrissigler 

[FeelingFinder-Linux-Portable.tar.gz](https://github.com/Merrit/feeling_finder/files/9758499/FeelingFinder-Linux-Portable.tar.gz)

Please give it a try and let me know if it works for you.

**Comment by chrissigler** [comment] 2022-10-13 14:28
@Merrit Seems to be working for me.

**Closed as completed** 2022-10-15 19:25 UTC
Labels: bug
